export const TOKSCALE_PROFILE_BASE_URL = "https://tokscale.ai";

export const TOKSCALE_CLIENT_DISPLAY_NAMES: Record<string, string> = {
  opencode: "OpenCode",
  claude: "Claude Code",
  codex: "Codex CLI",
  mcode: "MiniMax Code",
  copilot: "Copilot",
  gemini: "Gemini CLI",
  cursor: "Cursor",
  amp: "Amp",
  codebuff: "Codebuff",
  freebuff: "Freebuff",
  droid: "Droid",
  openclaw: "OpenClaw",
  hermes: "Hermes Agent",
  pi: "Pi",
  kimi: "Kimi",
  qwen: "Qwen",
  roocode: "Roo Code",
  kilocode: "Kilo",
  kilo: "Kilo",
  mux: "Mux",
  kiro: "Kiro",
  crush: "Crush",
  goose: "Goose",
  antigravity: "Antigravity",
  "antigravity-cli": "Antigravity CLI",
  zed: "Zed Agent",
  trae: "Trae",
  warp: "Warp",
  cline: "Cline",
  synthetic: "Synthetic",
  gjc: "Gajae Code",
  "9router": "9Router",
  grok: "Grok Build",
  jcode: "Jcode",
  commandcode: "Command Code",
  micode: "MiMo Code",
  junie: "Junie",
  zcode: "ZCode",
  opencodereview: "OpenCodeReview",
  codebuddy: "CodeBuddy",
  workbuddy: "WorkBuddy",
  "devin-cli": "Devin CLI",
  "devin-desktop": "Devin Desktop",
  senpi: "Senpi (OmO Native)",
  augment: "Augment Code",
  kimchi: "Kimchi",
  reasonix: "Reasonix",
  "prime-agent": "Prime Agent",
  cherrystudio: "Cherry Studio",
  dsh: "DeepSeek Harness",
  fx: "Fx",
  omp: "Oh My Pi",
  lmstudio: "LM Studio",
  unsloth: "Unsloth",
  hindsight: "Hindsight",
};
